### ISSUE TITLE
Anmelden Button

### ISSUE THREAD

**Issue by song-what** [Algram/abditory#5]
<img width="994" alt="bildschirmfoto 2016-02-24 um 9 13 56 pm" src="https://cloud.githubusercontent.com/assets/10561644/13300007/42efc4f8-db3e-11e5-99f7-c8babec37633.png">
Ich habe Anmelden Button auf der Landingseite so gesetzt, geht's so?

**Comment by Algram** [comment]
Den Button vielleicht ein bisschen kleiner und nur mit dem Text "Anmelden".
